package com.edupay.pay.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bit_pay_bank_account
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class PayBankAccount implements Serializable {
    /**
     * Database Column Remarks:
     *   支付账户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.pay_bank_account_id
     *
     * @mbg.generated
     */
    private Integer payBankAccountId;

    /**
     * Database Column Remarks:
     *   应用id;1教务平台;2官网平台
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.application_id
     *
     * @mbg.generated
     */
    private Integer applicationId;

    /**
     * Database Column Remarks:
     *   应用平台账户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.application_account_id
     *
     * @mbg.generated
     */
    private String applicationAccountId;

    /**
     * Database Column Remarks:
     *   账户类型：1银联;2支付宝;3微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.account_type
     *
     * @mbg.generated
     */
    private Integer accountType;

    /**
     * Database Column Remarks:
     *   账户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.bank_account_name
     *
     * @mbg.generated
     */
    private String bankAccountName;

    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.bank_account_no
     *
     * @mbg.generated
     */
    private String bankAccountNo;

    /**
     * Database Column Remarks:
     *   大客户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.partner_id
     *
     * @mbg.generated
     */
    private String partnerId;

    /**
     * Database Column Remarks:
     *   开户行
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.bank_name
     *
     * @mbg.generated
     */
    private String bankName;

    /**
     * Database Column Remarks:
     *   开户行网点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.bank_branch
     *
     * @mbg.generated
     */
    private String bankBranch;

    /**
     * Database Column Remarks:
     *   状态：1启用;0停用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   省市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   创建人用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bit_pay_bank_account.create_uid
     *
     * @mbg.generated
     */
    private String createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bit_pay_bank_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.pay_bank_account_id
     *
     * @return the value of bit_pay_bank_account.pay_bank_account_id
     *
     * @mbg.generated
     */
    public Integer getPayBankAccountId() {
        return payBankAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.pay_bank_account_id
     *
     * @param payBankAccountId the value for bit_pay_bank_account.pay_bank_account_id
     *
     * @mbg.generated
     */
    public void setPayBankAccountId(Integer payBankAccountId) {
        this.payBankAccountId = payBankAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.application_id
     *
     * @return the value of bit_pay_bank_account.application_id
     *
     * @mbg.generated
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.application_id
     *
     * @param applicationId the value for bit_pay_bank_account.application_id
     *
     * @mbg.generated
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.application_account_id
     *
     * @return the value of bit_pay_bank_account.application_account_id
     *
     * @mbg.generated
     */
    public String getApplicationAccountId() {
        return applicationAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.application_account_id
     *
     * @param applicationAccountId the value for bit_pay_bank_account.application_account_id
     *
     * @mbg.generated
     */
    public void setApplicationAccountId(String applicationAccountId) {
        this.applicationAccountId = applicationAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.account_type
     *
     * @return the value of bit_pay_bank_account.account_type
     *
     * @mbg.generated
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.account_type
     *
     * @param accountType the value for bit_pay_bank_account.account_type
     *
     * @mbg.generated
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.bank_account_name
     *
     * @return the value of bit_pay_bank_account.bank_account_name
     *
     * @mbg.generated
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.bank_account_name
     *
     * @param bankAccountName the value for bit_pay_bank_account.bank_account_name
     *
     * @mbg.generated
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.bank_account_no
     *
     * @return the value of bit_pay_bank_account.bank_account_no
     *
     * @mbg.generated
     */
    public String getBankAccountNo() {
        return bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.bank_account_no
     *
     * @param bankAccountNo the value for bit_pay_bank_account.bank_account_no
     *
     * @mbg.generated
     */
    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.partner_id
     *
     * @return the value of bit_pay_bank_account.partner_id
     *
     * @mbg.generated
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.partner_id
     *
     * @param partnerId the value for bit_pay_bank_account.partner_id
     *
     * @mbg.generated
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.bank_name
     *
     * @return the value of bit_pay_bank_account.bank_name
     *
     * @mbg.generated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.bank_name
     *
     * @param bankName the value for bit_pay_bank_account.bank_name
     *
     * @mbg.generated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.bank_branch
     *
     * @return the value of bit_pay_bank_account.bank_branch
     *
     * @mbg.generated
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.bank_branch
     *
     * @param bankBranch the value for bit_pay_bank_account.bank_branch
     *
     * @mbg.generated
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.status
     *
     * @return the value of bit_pay_bank_account.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.status
     *
     * @param status the value for bit_pay_bank_account.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.city
     *
     * @return the value of bit_pay_bank_account.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.city
     *
     * @param city the value for bit_pay_bank_account.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.remark
     *
     * @return the value of bit_pay_bank_account.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.remark
     *
     * @param remark the value for bit_pay_bank_account.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.create_date
     *
     * @return the value of bit_pay_bank_account.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.create_date
     *
     * @param createDate the value for bit_pay_bank_account.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bit_pay_bank_account.create_uid
     *
     * @return the value of bit_pay_bank_account.create_uid
     *
     * @mbg.generated
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bit_pay_bank_account.create_uid
     *
     * @param createUid the value for bit_pay_bank_account.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bit_pay_bank_account
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", payBankAccountId=").append(payBankAccountId);
        sb.append(", applicationId=").append(applicationId);
        sb.append(", applicationAccountId=").append(applicationAccountId);
        sb.append(", accountType=").append(accountType);
        sb.append(", bankAccountName=").append(bankAccountName);
        sb.append(", bankAccountNo=").append(bankAccountNo);
        sb.append(", partnerId=").append(partnerId);
        sb.append(", bankName=").append(bankName);
        sb.append(", bankBranch=").append(bankBranch);
        sb.append(", status=").append(status);
        sb.append(", city=").append(city);
        sb.append(", remark=").append(remark);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUid=").append(createUid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}